/* The following code was generated by JFlex 1.4.1 on 3/9/09 9:41 PM */

package ws.antonov.idea.plugin.protobuf.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import ws.antonov.idea.plugin.protobuf.lexer.ProtoTokenTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 3/9/09 9:41 PM from the specification file
 * <tt>/Users/aantonov/java-dev/ProtoBufPlugin/lexer/proto.flex</tt>
 */
public class _ProtobufLexer implements ProtoTokenTypes, FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\30\1\14"+
    "\1\0\1\30\1\0\1\30\1\0\1\4\1\5\1\30\1\30\1\3"+
    "\1\30\1\17\1\15\12\16\1\0\1\12\1\30\1\13\1\30\1\30"+
    "\1\0\32\30\1\6\1\31\1\7\1\0\1\30\1\0\1\25\1\30"+
    "\1\33\1\43\1\23\1\24\1\35\1\30\1\37\1\30\1\34\1\26"+
    "\1\41\1\40\1\36\1\32\1\44\1\21\1\27\1\20\1\22\2\30"+
    "\1\42\2\30\1\10\1\0\1\11\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\1\1\13\1\14\5\13\1\1"+
    "\3\13\1\0\1\15\1\13\2\0\10\13\1\0\2\16"+
    "\1\0\1\14\11\13\1\16\1\17\2\13\1\20\14\13"+
    "\1\21\2\13\1\22\1\13\1\23";

  private static int [] zzUnpackAction() {
    int [] result = new int[73];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\45\0\45\0\45\0\45\0\45"+
    "\0\45\0\45\0\45\0\157\0\224\0\271\0\336\0\u0103"+
    "\0\u0128\0\u014d\0\u0172\0\u0197\0\u01bc\0\u01e1\0\u0206\0\157"+
    "\0\45\0\u022b\0\u0197\0\u0250\0\u0275\0\u029a\0\u02bf\0\u02e4"+
    "\0\u0309\0\u032e\0\u0353\0\u0378\0\u039d\0\u03c2\0\45\0\u03e7"+
    "\0\u0250\0\u040c\0\u0431\0\u0456\0\u047b\0\u04a0\0\u04c5\0\u04ea"+
    "\0\u050f\0\u0534\0\u0559\0\336\0\u057e\0\u05a3\0\336\0\u05c8"+
    "\0\u05ed\0\u0612\0\u0637\0\u065c\0\u0681\0\u06a6\0\u06cb\0\u06f0"+
    "\0\u0715\0\u073a\0\u075f\0\u0784\0\u07a9\0\u07ce\0\336\0\u07f3"+
    "\0\336";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[73];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\17\1\22\1\23\4\17\1\24\1\25\3\17\1\26"+
    "\2\17\1\27\3\17\46\0\3\3\41\0\14\30\1\31"+
    "\30\30\15\0\1\32\13\17\1\33\13\17\16\0\1\16"+
    "\1\34\42\0\14\17\1\33\13\17\15\0\4\17\1\35"+
    "\7\17\1\33\13\17\15\0\6\17\1\36\5\17\1\33"+
    "\13\17\15\0\14\17\1\33\6\17\1\37\1\17\1\40"+
    "\2\17\15\0\10\17\1\41\3\17\1\33\15\17\1\0"+
    "\42\17\15\0\10\17\1\42\3\17\1\33\13\17\15\0"+
    "\14\17\1\33\1\43\12\17\15\0\6\17\1\44\5\17"+
    "\1\33\13\17\1\45\1\46\1\47\12\45\14\32\1\50"+
    "\13\32\16\0\1\51\43\0\5\17\1\52\6\17\1\33"+
    "\13\17\15\0\14\17\1\33\1\53\11\17\1\54\15\0"+
    "\5\17\1\55\6\17\1\33\13\17\15\0\3\17\1\56"+
    "\10\17\1\33\13\17\15\0\11\17\1\57\2\17\1\33"+
    "\13\17\15\0\14\17\1\33\1\17\1\60\11\17\15\0"+
    "\3\17\1\61\10\17\1\33\13\17\15\0\12\17\1\62"+
    "\1\17\1\33\13\17\1\45\1\46\1\47\42\45\2\0"+
    "\1\47\42\0\1\32\1\63\1\47\42\32\15\0\6\17"+
    "\1\64\5\17\1\33\13\17\15\0\6\17\1\65\5\17"+
    "\1\33\13\17\15\0\5\17\1\66\6\17\1\33\13\17"+
    "\15\0\14\17\1\33\7\17\1\67\3\17\15\0\6\17"+
    "\1\70\5\17\1\33\13\17\15\0\12\17\1\52\1\17"+
    "\1\33\13\17\15\0\14\17\1\33\2\17\1\71\10\17"+
    "\15\0\14\17\1\33\5\17\1\72\5\17\15\0\12\17"+
    "\1\73\1\17\1\33\13\17\2\0\1\47\12\0\14\17"+
    "\1\33\13\17\15\0\10\17\1\74\3\17\1\33\13\17"+
    "\15\0\14\17\1\33\5\17\1\75\5\17\15\0\14\17"+
    "\1\33\6\17\1\76\4\17\15\0\10\17\1\77\3\17"+
    "\1\33\13\17\15\0\14\17\1\33\4\17\1\100\6\17"+
    "\15\0\10\17\1\101\3\17\1\33\13\17\15\0\3\17"+
    "\1\102\10\17\1\33\13\17\15\0\4\17\1\102\7\17"+
    "\1\33\13\17\15\0\14\17\1\33\11\17\1\67\1\17"+
    "\15\0\14\17\1\33\3\17\1\103\7\17\15\0\14\17"+
    "\1\33\6\17\1\104\4\17\15\0\14\17\1\33\3\17"+
    "\1\105\7\17\15\0\6\17\1\106\5\17\1\33\13\17"+
    "\15\0\6\17\1\107\5\17\1\33\13\17\15\0\10\17"+
    "\1\110\3\17\1\33\13\17\15\0\6\17\1\67\5\17"+
    "\1\33\13\17\15\0\14\17\1\33\11\17\1\111\1\17"+
    "\15\0\11\17\1\111\2\17\1\33\13\17";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2072];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\10\11\14\1\1\0\1\11\1\1"+
    "\2\0\10\1\1\0\1\1\1\11\1\0\41\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[73];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public _ProtobufLexer(boolean highlightMode) {
      this((java.io.Reader)null);
      isHighlightModeOn = highlightMode;
    }

    private boolean isHighlightModeOn = false;



  public _ProtobufLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _ProtobufLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  // For Demetra compatibility
  public void reset(CharSequence buffer, int initialState){
    zzBuffer = buffer;
    zzBufferArray = null; 
    zzCurrentPos = zzMarkedPos = zzStartRead = 0;
    zzPushbackPos = 0;
    zzAtEOF = false;
    zzAtBOL = true;
    zzEndRead = buffer.length();
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = zzLexicalState;


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 7: 
          { return LEFT_CURLY;
          }
        case 20: break;
        case 19: 
          { return FIELD_DEF;
          }
        case 21: break;
        case 14: 
          { return COMMENT;
          }
        case 22: break;
        case 11: 
          { return KEY;
          }
        case 23: break;
        case 1: 
          { return BAD_CHARACTER;
          }
        case 24: break;
        case 3: 
          { return LEFT_PAREN;
          }
        case 25: break;
        case 17: 
          { return OPTION;
          }
        case 26: break;
        case 6: 
          { return RIGHT_BRACKET;
          }
        case 27: break;
        case 4: 
          { return RIGHT_PAREN;
          }
        case 28: break;
        case 10: 
          { return EQUALS;
          }
        case 29: break;
        case 13: 
          { return STRING_LITERAL;
          }
        case 30: break;
        case 12: 
          { return NUMERIC_LITERAL;
          }
        case 31: break;
        case 2: 
          { return WHITE_SPACE;
          }
        case 32: break;
        case 9: 
          { return SEMICOLON;
          }
        case 33: break;
        case 5: 
          { return LEFT_BRACKET;
          }
        case 34: break;
        case 8: 
          { return RIGHT_CURLY;
          }
        case 35: break;
        case 18: 
          { return PACKAGE;
          }
        case 36: break;
        case 15: 
          { return BOOLEAN_LITERAL;
          }
        case 37: break;
        case 16: 
          { return OBJECT_DEF;
          }
        case 38: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
